### ISSUE TITLE
allowHalfRating gone wrong

### ISSUE THREAD

**Issue by dungnv2602** [thangmam/smoothratingbar#13]
`
                          SmoothStarRating(
                            allowHalfRating: true,
                            rating: novel.rating,
                            starCount: 10,
                            size: 16,
                            color: theme.accentColor,
                            borderColor: theme.accentColor,
                            spacing: 0.0,
                          )
`
![allowHalfRating_false](https://user-images.githubusercontent.com/19910775/64150420-65149a80-ce52-11e9-8be4-03064ede5343.png)

The code above was supposed to disallow half rating but it actually did allow, and vice versa. I believe there sth wrong in your conditional checking in your code.

`
                          SmoothStarRating(
                            allowHalfRating: true,
                            rating: novel.rating,
                            starCount: 10,
                            size: 16,
                            color: theme.accentColor,
                            borderColor: theme.accentColor,
                            spacing: 0.0,
                          )
`
![allowHalfRating_true](https://user-images.githubusercontent.com/19910775/64150422-65ad3100-ce52-11e9-9b0b-21e17694ac6b.png)

**Comment by thangmam** [comment]
Hi there, the first code you posted has allowHalfRating set to true , so you will get half rated stars as you posted in the first image which is the expected behaviour.The second code you posted also has allowHalfRating set to true(This may be typo on your side,Please recheck your code again) .Looking at the second image, the parameter allowHalfRating =false should give something similar to second image.I am closing this for now.Dont hesitate to open it again.Thanks
