### ISSUE TITLE
allowHalfRating flag working in opposite manner

### ISSUE THREAD

**Issue by abhijeetvader9287** [thangmam/smoothratingbar#15]
In smooth_star_rating: 1.0.3 , when allowHalfRating=true it is showing full star and allowHalfRating=false it is showing half star.

**Comment by thangmam** [comment]
hello , i have rechecked the library and its working as expected , i.e When allowHalfRating=true , then i get half rated stars and when allowHalfRating=false, i get full rated stars.Please check it again.Try removing allowHalfRating from constructor and check if you get half rated stars or not.Since by default , allowHalfRating is set to true.You will be getting half rated stars.I will close this for now .Dont hesitate to reopen it again.Thanks
