### ISSUE TITLE
allowHalfRating Fix

### ISSUE THREAD

**Issue by essare** [thangmam/smoothratingbar#2]
this code shows halfRating if allowHalfRating is set to false
```Dart
SmoothStarRating(
      allowHalfRating: false, <--- this actually enables halfRating so it has to be true not false
      starCount: 5,
      rating: 2.5,
      size: 20.0,
      color: Colors.orange,
      borderColor: Colors.grey,
            ),
```

this code disallow halfRating if allowHalfRating is set to true
``` Dart
SmoothStarRating(
      allowHalfRating: true, <--- this actually enables halfRating so it has to be false not true
      starCount: 5,
      rating: 2.5,
      size: 20.0,
      color: Colors.orange,
      borderColor: Colors.grey,
            ),
```

**Comment by thangmam** [comment]
@Ess-Soft Hello,I am not observing the behaviour you mentioned.When allowHalfRating is set to "false" , half rating is disabled and when allowHalfRating is set to "true" ,  half rating is enabled which is the expected behaviour.BTW, the version is tested is 1.0.1 . Confirm this when you can and do let me know.Thanks

**Comment by ronpetit** [comment]
Hello @thangmam, I'm having this problem over a Nexus 5X, Android 8.1, flutter 1.7.8, and your plugin version 1.0.3, if set ```allowHalfRating``` to ```true``` it actually doesn't let me use half stars, but if I set it to ```false``` it will
