### ISSUE TITLE
Support RTL

### ISSUE THREAD

**Issue by p30arena** [thangmam/smoothratingbar#6]
Drag is reverse and Half Star not showing
```
SmoothStarRating(
                      rating: 2.5,
                      starCount: 5,
                      size: 20,
                      allowHalfRating: true,
                      color: Colors.yellow,
                      borderColor: Colors.white,
                    ),
```

**Comment by thangmam** [comment]
hello, thanks for the pull request.I am unable to replicate the issue **Drag is reverse and Half Star not showing**  you mentioned.Maybe my approach is wrong.I have enabled the **Force RTL layout Direction** from the developer to test it.Let me know how i can replicate it.Thanks

**Comment by ykabbara** [comment]
Hello, Thanks for the greate job @thangmam, is it solved if yes is there any chance to show how to use it RTL?
Best

**Comment by thangmam** [comment]
@ykabbara  hi, i am waiting for @p30arena  to reply since i am unable to replicate the issue **Drag is reverse and Half Star not showing**.You may also check it yourself and report the issue you are facing, if i can atleast replicate it on my device, then i would be already half way to solving the issue.

**Comment by thangmam** [comment]
The patch from @p30arena has bugs and i cannot merge it for now.The bug is related to allowHalfRating set to true/false. @p30arena If you can fix this, i will be happy to merge it.Thanks
